/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 planets_gltf.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/planets_gltf.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Clouds" geometry={nodes.Clouds.geometry} material={materials.PM3D_Sphere3D1} scale={0.03} />
        <mesh name="Island_1" geometry={nodes.Island_1.geometry} material={materials.PM3D_Sphere3D_8} position={[0.04, 0.02, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
        <mesh name="Island_5" geometry={nodes.Island_5.geometry} material={materials.PM3D_Sphere3D_8} position={[0.04, 0, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
        <mesh name="Island_3" geometry={nodes.Island_3.geometry} material={materials.PM3D_Sphere3D_8} position={[0.02, 0, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
        <mesh name="Island_4" geometry={nodes.Island_4.geometry} material={materials.PM3D_Sphere3D_8} position={[0, 0, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
        <mesh name="Island_2" geometry={nodes.Island_2.geometry} material={materials.PM3D_Sphere3D_8} position={[0, 0, 0.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.02} />
        <mesh name="Line_island_1" geometry={nodes.Line_island_1.geometry} material={materials.PM3D_Sphere3D_8} />
        <mesh name="Line_island_4" geometry={nodes.Line_island_4.geometry} material={materials.PM3D_Sphere3D_8} />
        <mesh name="Line_island_5" geometry={nodes.Line_island_5.geometry} material={materials.PM3D_Sphere3D_8} />
        <mesh name="line_island_3" geometry={nodes.line_island_3.geometry} material={materials.PM3D_Sphere3D_8} />
        <mesh name="line_island_2" geometry={nodes.line_island_2.geometry} material={materials.PM3D_Sphere3D_8} />
        <mesh name="Planet" geometry={nodes.Planet.geometry} material={materials.PM3D_Sphere3D2} />
      </group>
    </group>
  )
}

useGLTF.preload('/planets_gltf.glb')
