/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.0 jeep-c.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Jeep(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/garage/jeep-c.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group>
        <group name="jeep" rotation={[-Math.PI / 2, 0, 0]} scale={162.21}>
          <mesh
            name="jeep-Material_#2146931172"
            geometry={nodes["jeep-Material_#2146931172"].geometry}
            material={materials["Material #2146931172"]}
          />
          <mesh
            name="jeep-Material_#2146931134"
            geometry={nodes["jeep-Material_#2146931134"].geometry}
            material={materials["Material #2146931134"]}
          />
          <mesh
            name="jeep-Material_#2146931063"
            geometry={nodes["jeep-Material_#2146931063"].geometry}
            material={materials["Material #2146931063"]}
          />
          <mesh
            name="jeep-Material_#2146931003"
            geometry={nodes["jeep-Material_#2146931003"].geometry}
            material={materials["Material #2146931003"]}
          />
          <mesh
            name="jeep-Material_008"
            geometry={nodes["jeep-Material_008"].geometry}
            material={materials.Material_008}
          />
          <mesh
            name="jeep-Material_012"
            geometry={nodes["jeep-Material_012"].geometry}
            material={materials.Material_012}
          />
          <mesh
            name="jeep-Material_#2146931159"
            geometry={nodes["jeep-Material_#2146931159"].geometry}
            material={materials["Material #2146931159"]}
          />
          <mesh
            name="jeep-Material_#2146931165"
            geometry={nodes["jeep-Material_#2146931165"].geometry}
            material={materials["Material #2146931165"]}
          />
          <mesh
            name="jeep-Material_#2146931164"
            geometry={nodes["jeep-Material_#2146931164"].geometry}
            material={materials["Material #2146931164"]}
          />
          <mesh
            name="jeep-None"
            geometry={nodes["jeep-None"].geometry}
            material={materials.None}
          />
          <mesh
            name="jeep-Material_004"
            geometry={nodes["jeep-Material_004"].geometry}
            material={materials.Material_004}
          />
          <mesh
            name="jeep-Axles"
            geometry={nodes["jeep-Axles"].geometry}
            material={materials.Axles}
          />
          <mesh
            name="jeep-Material_#2146931167"
            geometry={nodes["jeep-Material_#2146931167"].geometry}
            material={materials["Material #2146931167"]}
          />
          <mesh
            name="jeep-Material_#2146931171"
            geometry={nodes["jeep-Material_#2146931171"].geometry}
            material={materials["Material #2146931171"]}
          />
          <mesh
            name="jeep-Material_#2146931114"
            geometry={nodes["jeep-Material_#2146931114"].geometry}
            material={materials["Material #2146931114"]}
          />
          <mesh
            name="jeep-Material_#2146931163"
            geometry={nodes["jeep-Material_#2146931163"].geometry}
            material={materials["Material #2146931163"]}
          />
          <mesh
            name="jeep-Material_#2146931158"
            geometry={nodes["jeep-Material_#2146931158"].geometry}
            material={materials["Material #2146931158"]}
          />
          <mesh
            name="jeep-Material_#2146931160"
            geometry={nodes["jeep-Material_#2146931160"].geometry}
            material={materials["Material #2146931160"]}
          />
          <mesh
            name="jeep-Material_#2146931157"
            geometry={nodes["jeep-Material_#2146931157"].geometry}
            material={materials["Material #2146931157"]}
          />
          <mesh
            name="jeep-Material_#2146931132"
            geometry={nodes["jeep-Material_#2146931132"].geometry}
            material={materials["Material #2146931132"]}
          />
          <mesh
            name="jeep-Material_#2146931169"
            geometry={nodes["jeep-Material_#2146931169"].geometry}
            material={materials["Material #2146931169"]}
          />
          <mesh
            name="jeep-Material_#2146931170"
            geometry={nodes["jeep-Material_#2146931170"].geometry}
            material={materials["Material #2146931170"]}
          />
          <mesh
            name="jeep-Material_#2146931130"
            geometry={nodes["jeep-Material_#2146931130"].geometry}
            material={materials["Material #2146931130"]}
          />
          <mesh
            name="jeep-Glass_Bumpy_02_10cm_#0"
            geometry={nodes["jeep-Glass_Bumpy_02_10cm_#0"].geometry}
            material={materials["Glass_Bumpy_02_10cm #0"]}
          />
          <mesh
            name="jeep-Material_#2146931168"
            geometry={nodes["jeep-Material_#2146931168"].geometry}
            material={materials["Material #2146931168"]}
          />
          <mesh
            name="jeep-Material_#2146932897"
            geometry={nodes["jeep-Material_#2146932897"].geometry}
            material={materials["Material #2146932897"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/garage/jeep-c.glb");
