/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car1-c.glb
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Car1(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("garage/car1-c.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Circle" rotation={[Math.PI / 2, 0, 0]} />
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        >
          {/* <meshStandardMaterial attach="material" map={texture} /> */}
        </mesh>
        <mesh
          name="Plane_003"
          geometry={nodes.Plane_003.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_001_Plane_004"
          geometry={nodes.Plane_001_Plane_004.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_002_Plane_006"
          geometry={nodes.Plane_002_Plane_006.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_004_Plane_007"
          geometry={nodes.Plane_004_Plane_007.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_005_Plane_008"
          geometry={nodes.Plane_005_Plane_008.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_007_Plane_010"
          geometry={nodes.Plane_007_Plane_010.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_006_Plane_011"
          geometry={nodes.Plane_006_Plane_011.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_008_Plane_013"
          geometry={nodes.Plane_008_Plane_013.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_009_Plane_014"
          geometry={nodes.Plane_009_Plane_014.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_Cube_001"
          geometry={nodes.Cube_Cube_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_010"
          geometry={nodes.Plane_010.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_011_Plane_016"
          geometry={nodes.Plane_011_Plane_016.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_001_Cube_002"
          geometry={nodes.Cube_001_Cube_002.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_002_Cube_003"
          geometry={nodes.Cube_002_Cube_003.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_003_Cube_004"
          geometry={nodes.Cube_003_Cube_004.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_003_Plate_Cube_004_Plate"
          geometry={nodes.Cube_003_Plate_Cube_004_Plate.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_004_Cube_005"
          geometry={nodes.Cube_004_Cube_005.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_005_Cube"
          geometry={nodes.Cube_005_Cube.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_006"
          geometry={nodes.Cube_006.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_Plate_Cube_001_Plate"
          geometry={nodes.Cube_Plate_Cube_001_Plate.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_007"
          geometry={nodes.Cube_007.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_011_Cube_009"
          geometry={nodes.Cube_011_Cube_009.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_012_Plane_001"
          geometry={nodes.Plane_012_Plane_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_001"
          geometry={nodes.Cylinder_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_008_Cube_010"
          geometry={nodes.Cube_008_Cube_010.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_002"
          geometry={nodes.Cylinder_002.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_003"
          geometry={nodes.Cylinder_003.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_013_Plane_002"
          geometry={nodes.Plane_013_Plane_002.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_014_Plane_005"
          geometry={nodes.Plane_014_Plane_005.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_015_Plane_009"
          geometry={nodes.Plane_015_Plane_009.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_012_Cube_018"
          geometry={nodes.Cube_012_Cube_018.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_013_Cube_019"
          geometry={nodes.Cube_013_Cube_019.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_004"
          geometry={nodes.Cylinder_004.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Lancer_Evolution_10_001"
          geometry={nodes.Lancer_Evolution_10_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_016_Plane_017"
          geometry={nodes.Plane_016_Plane_017.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Lancer_Evolution_10_003"
          geometry={nodes.Lancer_Evolution_10_003.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_016_Plate_Plane_017_Plate"
          geometry={nodes.Plane_016_Plate_Plane_017_Plate.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_017_Plane_012"
          geometry={nodes.Plane_017_Plane_012.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_018_Plane_015"
          geometry={nodes.Plane_018_Plane_015.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_Plate"
          geometry={nodes.Plane_Plate.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_005"
          geometry={nodes.Cylinder_005.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Plane_019"
          geometry={nodes.Plane_019.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_006"
          geometry={nodes.Cylinder_006.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_016_Cube_012"
          geometry={nodes.Cube_016_Cube_012.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_007_Cylinder_008"
          geometry={nodes.Cylinder_007_Cylinder_008.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Retopo_Lancer_Evolution_10_001_mesh_002"
          geometry={nodes.Retopo_Lancer_Evolution_10_001_mesh_002.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cylinder_008_Cylinder_007"
          geometry={nodes.Cylinder_008_Cylinder_007.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="Cube_017_Cube_008"
          geometry={nodes.Cube_017_Cube_008.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="mesh_id44_001"
          geometry={nodes.mesh_id44_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
        <mesh
          name="mesh_id84_001"
          geometry={nodes.mesh_id84_001.geometry}
          material={materials["Material #129"]}
          scale={0.01}
        />
      </group>
    </group>
  );
}

useGLTF.preload("garage/car1-c.glb");
