/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car_new.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Car12(props) {
  const { nodes, materials } = useGLTF("./garage/car_new.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_003.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_001_Plane_004.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_002_Plane_006.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_004_Plane_007.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_005_Plane_008.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_007_Plane_010.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_006_Plane_011.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_008_Plane_013.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_009_Plane_014.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_Cube_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_010.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_011_Plane_016.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_001_Cube_002.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_002_Cube_003.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_003_Cube_004.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_003_Plate_Cube_004_Plate.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_004_Cube_005.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_005_Cube.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_006.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_Plate_Cube_001_Plate.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_007.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_011_Cube_009.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_012_Plane_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_008_Cube_010.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_002.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_003.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_013_Plane_002.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_014_Plane_005.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_015_Plane_009.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_012_Cube_018.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_013_Cube_019.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_004.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Lancer_Evolution_10_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_016_Plane_017.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Lancer_Evolution_10_003.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_016_Plate_Plane_017_Plate.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_017_Plane_012.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_018_Plane_015.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_Plate.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_005.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_019.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_006.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_016_Cube_012.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_007_Cylinder_008.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Retopo_Lancer_Evolution_10_001_mesh_002.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder_008_Cylinder_007.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube_017_Cube_008.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_id44_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.mesh_id84_001.geometry}
        material={materials["Material #129"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("./garage/car_new.glb");
