/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 moto-c.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Moto(props) {
  const { nodes, materials } = useGLTF("/garage/moto-c.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials["Material.002"]}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.002"]}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.wire_177088027}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.04, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.006"]}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder001_Plate.geometry}
        material={materials["Material.006"]}
        position={[0.76, -0.01, 0.16]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.001"]}
        position={[0.73, -0.01, 0.22]}
        rotation={[0, 0, 0.44]}
        scale={0.94}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.006"]}
        position={[0.59, 0.27, 0.22]}
        rotation={[0, 0, 0.44]}
        scale={0.94}
      />
      <mesh
        geometry={nodes.Cylinder003_Plate.geometry}
        material={materials["Material.001"]}
        position={[0.37, 0.75, 0.22]}
        rotation={[0, 0, 0.44]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.001"]}
        position={[0.34, 0.74, 0.22]}
        rotation={[0, 0, 0.44]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.001"]}
        position={[0.33, 0.75, 0.22]}
        rotation={[0, 0, 0.41]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[0.44, 0.78, 0.14]}
        rotation={[0, 0, 0.44]}
        scale={[0.9, 1, 0.9]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.001"]}
        position={[0.56, 0.6, 0.14]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.004"]}
        position={[0.56, 0.6, 0.14]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["Material.004"]}
        position={[0.44, 0.78, 0.14]}
        rotation={[0, 0, 0.44]}
        scale={[0.9, 1, 0.9]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["Material.001"]}
        position={[-0.75, 0.73, 0.14]}
        scale={[0.25, 0.25, 0.14]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.Material}
        position={[-0.31, 0.7, 0.14]}
        scale={[0.3, 0.3, 0.17]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials["Material.001"]}
        position={[-0.34, 0.51, 0.24]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials["Material.003"]}
        position={[-0.98, 0.68, 0.14]}
        rotation={[0, 0, 0.41]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.006"]}
        position={[-0.71, 0.53, 0.22]}
        rotation={[0, 0.1, 1.2]}
        scale={0.86}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials["Material.001"]}
        position={[-0.08, 0.53, 0.23]}
        rotation={[Math.PI / 2, 0, -0.12]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Material.001"]}
        position={[-0.02, 0.34, 0.25]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.008"]}
        position={[-0.95, 0.7, 0.14]}
        scale={[1, 1, 1.52]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Material.001"]}
        position={[0.45, 0.77, 0.2]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials["Material.006"]}
        position={[0.31, 0.78, 0.14]}
        rotation={[0, 0, 0.65]}
        scale={0.12}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.Material}
        position={[0.27, 0.88, 0.4]}
        rotation={[Math.PI / 2, 0.65, 0]}
        scale={0.93}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.006"]}
        position={[0.26, 0.76, 0.14]}
        scale={[-0.04, -0.01, -0.04]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials["Material.002"]}
        position={[0.16, 0.67, 0.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.05}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={materials["Material.006"]}
        position={[0.76, -0.01, 0.11]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={materials["Material.001"]}
        position={[0.76, -0.01, 0.12]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.03}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.Material}
        position={[0.76, 0.06, 0.1]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials["Material.002"]}
        position={[-0.15, 0.49, 0.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.06}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials["Material.006"]}
        position={[0.44, 0.86, 0.14]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.22}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials["Material.007"]}
        position={[0.52, 0.68, 0.14]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={0.84}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.Material}
        position={[-0.49, 0.62, 0.26]}
        rotation={[1.29, 0, 0]}
        scale={[-0.01, 0, -0.01]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.Material}
        position={[-0.2, 0.52, 0.27]}
        rotation={[1.62, -0.26, -0.1]}
        scale={[-0.01, 0, -0.01]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.Material}
        position={[-0.31, 0.35, 0.27]}
        rotation={[1.56, -0.25, -0.08]}
        scale={[-0.01, 0, -0.01]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials["Material.006"]}
        position={[0.32, 0.72, 0.17]}
        rotation={[0, 0.22, -0.75]}
      />
      <mesh
        geometry={nodes.Circle003.geometry}
        material={materials["Material.002"]}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.002"]}
        position={[-0.74, 0, 0.23]}
        rotation={[0, 0, 0.27]}
        scale={[1, 1, 1.17]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["default"]}
        position={[-0.24, 0.11, 0.21]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials["Material.004"]}
        position={[0.34, 0.88, 0.34]}
        rotation={[0, 0, -1.37]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials["Material.006"]}
        position={[0.34, 0.88, 0.34]}
        rotation={[0, 0, -1.37]}
        scale={[0.84, 1, 1]}
      />
      <mesh
        geometry={nodes.KTM003.geometry}
        material={materials.wire_177088027}
        position={[-0.28, 0.1, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Material.006"]}
        position={[-0.02, 0.04, 0.14]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials["Material.001"]}
        position={[0.09, 0.16, 0.17]}
        rotation={[0, 0, -0.39]}
      />
      <mesh
        geometry={nodes.Circle004.geometry}
        material={materials["Material.006"]}
        position={[-0.15, 0.15, 0.28]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials["Material.006"]}
        position={[-0.15, 0.25, 0.25]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials["Material.002"]}
        position={[-0.28, 0.13, 0.24]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials["Material.004"]}
        position={[-0.28, 0.31, 0.26]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials.Material}
        position={[-0.27, 0.26, 0.26]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-0.01, 0, -0.01]}
      />
      <mesh
        geometry={nodes.KTM007.geometry}
        material={materials.wire_177088027}
        position={[0.07, 0.4, 0.14]}
        rotation={[Math.PI / 2, -0.15, 0]}
        scale={1.17}
      />
      <mesh
        geometry={nodes.KTM005.geometry}
        material={materials["Material.006"]}
        position={[-0.3, 0.3, 0.14]}
        rotation={[Math.PI / 2, 0.14, 0]}
        scale={0.77}
      />
      <mesh
        geometry={nodes.KTM010.geometry}
        material={materials["Material.006"]}
        position={[-0.3, 0.3, 0.14]}
        rotation={[Math.PI / 2, 0.14, 0]}
        scale={0.78}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials["Material.001"]}
        position={[0.13, 0.23, 0.13]}
        rotation={[0, 0, -1.96]}
        scale={1.1}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials.wire_177088027}
        position={[0.12, 0.4, 0.14]}
        rotation={[0, 0, -0.43]}
        scale={-0.01}
      />
      <mesh
        geometry={nodes.KTM006.geometry}
        material={materials.wire_177088027}
        position={[0.08, 0.4, 0.14]}
        rotation={[Math.PI / 2, -0.15, 0]}
      />
      <mesh
        geometry={nodes.BezierCurve.geometry}
        material={materials["Material.002"]}
        position={[0.17, 0.62, 0.26]}
        rotation={[0, 0, -1.75]}
        scale={0.3}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_032001.geometry}
        material={materials.Material}
        position={[0.03, 0.25, 0.14]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Retopo_Archmodels_93_001_010001.geometry}
        material={materials["Material.001"]}
        position={[0.28, 0.89, 0.07]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials["Material.004"]}
        position={[0.1, 0.3, 0.24]}
        rotation={[0.27, 0, -0.01]}
        scale={[1.34, 0.9, 1.34]}
      />
      <mesh
        geometry={nodes.Retopo_Archmodels_93_001_007002.geometry}
        material={materials.wire_177088027}
        position={[-0.44, 0.48, 0.14]}
        rotation={[0, 0, -0.06]}
        scale={[0.12, 0.09, 0.1]}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_026001.geometry}
        material={materials["Material.006"]}
        position={[-0.08, 0.32, 0.14]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials["Material.004"]}
        position={[0.13, 0.63, 0.27]}
        rotation={[0, 0, -3.02]}
        scale={[1.15, 0.77, 0.98]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={materials["Material.001"]}
        position={[0.26, 0.63, 0.24]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.BezierCurve001.geometry}
        material={materials["Material.006"]}
        position={[0.24, 0.23, 0.13]}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_023001.geometry}
        material={materials.wire_177088027}
        position={[0, 0.32, 0.14]}
        rotation={[0, 0, -0.08]}
        scale={[1, 1, 0.74]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials["Material.006"]}
        position={[-0.29, 0.43, 0.23]}
        rotation={[0, 0, -0.42]}
      />
      <mesh
        geometry={nodes.NurbsPath.geometry}
        material={materials.Material}
        position={[0.1, 0.23, 0.24]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={-0.03}
      />
      <mesh
        geometry={nodes.KTM008.geometry}
        material={materials.wire_177088027}
        position={[0.24, 0.5, 0.17]}
        rotation={[1.5, 0.6, 0.04]}
        scale={0.56}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials.wire_177088027}
        position={[-0.15, 0.49, 0.23]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.06, 0.02, 0.06]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials["Material.006"]}
        position={[-0.29, 0.12, 0.24]}
        rotation={[Math.PI / 2, 0.2, 0]}
        scale={0.75}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials["Material.006"]}
        position={[-0.29, 0.12, 0.26]}
        rotation={[Math.PI / 2, 0.2, 0]}
        scale={[-0.01, 0, -0.01]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={materials["Material.006"]}
        position={[-0.02, 0.04, 0.14]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[0.1, 0.19, 0.11]}
        rotation={[0, 0, -0.39]}
        scale={[0.61, 1, 1]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials["Material.006"]}
        position={[-0.31, 0.12, 0.25]}
        rotation={[Math.PI / 2, 0.21, 0]}
        scale={1.25}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials["Material.006"]}
        position={[-0.26, 0.13, 0.24]}
        rotation={[Math.PI / 2, 0.17, 0]}
        scale={1.26}
      />
      <mesh
        geometry={nodes.KTM002.geometry}
        material={materials.wire_177088027}
        position={[-0.15, 0.3, 0.2]}
        rotation={[-1.45, -1.07, 0.11]}
        scale={[1.14, -1.14, 1.14]}
      />
      <mesh
        geometry={nodes.KTM009.geometry}
        material={materials.wire_177088027}
        position={[-0.46, 0.36, 0.2]}
        rotation={[1.67, -0.52, -2.99]}
        scale={[1.14, -1.14, 1.14]}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_044001.geometry}
        material={materials.wire_177088027}
        position={[-0.15, 0.31, 0.3]}
        rotation={[0, -0.07, 0.59]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Retopo_Archmodels_93_001_025001.geometry}
        material={materials["Material.006"]}
        position={[-0.2, 0.26, 0.28]}
        rotation={[0, -0.07, 0.59]}
        scale={0.09}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials["Material.006"]}
        position={[-0.24, 0.23, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.79}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.006"]}
        position={[-0.24, 0.08, 0.23]}
        rotation={[0, 0, 0.73]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Material.006"]}
        position={[-0.25, 0.08, 0.26]}
        rotation={[0, 0, 0.39]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={materials["Material.006"]}
        position={[-0.23, 0.09, 0.25]}
        rotation={[0, 0, 0.39]}
        scale={[0, -0.01, -0.01]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={materials["Material.006"]}
        position={[-0.23, 0.09, 0.26]}
        rotation={[1.79, 0.38, -1.65]}
        scale={0}
      />
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials.Material}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials.Material}
        position={[0.76, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle007.geometry}
        material={materials.Material}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle008.geometry}
        material={materials.Material}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={materials["Material.002"]}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={materials.wire_177088027}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.05, 0.04, 0.05]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={materials.wire_177088027}
        position={[-0.73, -0.01, 0.14]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle010.geometry}
        material={materials["Material.006"]}
        position={[-0.73, -0.01, 0.11]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.03}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_029001.geometry}
        material={materials["Material.006"]}
        position={[0.03, 0.36, 0.2]}
        rotation={[0, 0, 0.09]}
        scale={0.1}
      />
      <mesh
        geometry={nodes.Archmodels_93_001_023002.geometry}
        material={materials.wire_177088027}
        position={[0, 0.32, 0.14]}
        rotation={[0, 0, -0.08]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials["Material.004"]}
        position={[0.13, 0.59, 0.26]}
        rotation={[0, 0, 0.1]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.004"]}
        position={[0.14, 0.5, 0.26]}
        rotation={[0, 0, 0.1]}
        scale={1.02}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={materials["Material.002"]}
        position={[-0.02, 0.35, 0.28]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/garage/moto-c.glb");
