/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car-c.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Car(props) {
  const { nodes, materials } = useGLTF("/garage/car-c.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_id44001.geometry}
        material={materials["Material.003"]}
        position={[0, -0.35, -0.05]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[1.01, 1.01, 1.27]}
      />
      <mesh
        geometry={nodes.mesh_id84001.geometry}
        material={materials["Material.009"]}
        position={[0.01, -0.29, -0.11]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={1.01}
      />
      <group position={[0, 0, 2.21]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane_1.geometry} material={materials.Material} />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          geometry={nodes.Plane_3.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials["Material.006"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={materials["Material.001"]}
        position={[-0.68, 0.72, -0.85]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials["Material.001"]}
        position={[-0.68, 0.72, -0.85]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane004.geometry}
        material={materials["Material.006"]}
        position={[0, -0.01, 2.2]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["em.001"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.em}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials["Material.006"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.Material}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        position={[0, -0.05, 2.36]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={materials["Material.002"]}
        position={[-0.61, 0.04, 2.34]}
        scale={-0.02}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={materials["Material.001"]}
        position={[-0.93, -0.19, -0.4]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={materials["Material.002"]}
        position={[-0.15, 0.2, 2.37]}
        scale={[1, 1.19, 1]}
      />
      <group position={[-0.15, 0.2, 2.37]} scale={[1, 1.19, 1]}>
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.em} />
      </group>
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Material.008"]}
        position={[0, -0.04, 2.28]}
      />
      <mesh
        geometry={nodes.Cube003_Plate.geometry}
        material={materials["Material.002"]}
        position={[0, -0.04, 2.28]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials["Material.003"]}
        position={[0, -0.04, 2.28]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={materials.Material}
        position={[-0.2, 0, 2.29]}
        scale={0.91}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={materials.Material}
        position={[-0.45, -0.02, 2.27]}
      />
      <mesh
        geometry={nodes.Cube_Plate.geometry}
        material={materials["Material.002"]}
        position={[0, -0.05, 2.36]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Material.009"]}
        position={[-0.82, 0, 2.27]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={materials["Material.003"]}
        position={[0, -0.05, 2.3]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials["Material.009"]}
        position={[-0.46, -0.09, 2.43]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials["Material.005"]}
        position={[-0.45, -0.09, 2.45]}
        rotation={[0, -0.05, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials["Material.009"]}
        position={[-0.51, -0.05, 2.43]}
        rotation={[Math.PI / 2, 0, 0.05]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={materials["Material.009"]}
        position={[0, -0.1, 2.45]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.009"]}
        position={[-0.13, -0.1, 2.45]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1.58, 1.34, 1.58]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials["Material.003"]}
        position={[-0.2, 0.04, 2.3]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials["em.001"]}
        position={[0, -0.03, 2.27]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={1.07}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.001"]}
        position={[0, -0.23, 2.14]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Material.009"]}
        position={[0, -0.05, 2.36]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials["Material.009"]}
        position={[-0.63, 0.07, 2.35]}
        rotation={[0, 0, -0.56]}
      />
      <mesh
        geometry={nodes.Lancer_Evolution_10001.geometry}
        material={materials["Material.003"]}
        position={[0.02, 0.02, -0.02]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials["Material.001"]}
        position={[-0.88, 0.58, 0.64]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Lancer_Evolution_10003.geometry}
        material={materials["Material.001"]}
        position={[-0.89, 0.38, -0.1]}
        rotation={[0, -0.02, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Plane016_Plate.geometry}
        material={materials.Material}
        position={[-0.88, 0.58, 0.64]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={materials.Material}
        position={[0, 0.89, -2.21]}
        scale={[1, 1.12, 1]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={materials["Material.001"]}
        position={[-0.7, 0.16, -1.86]}
      />
      <mesh
        geometry={nodes.Plane_Plate.geometry}
        material={materials["Material.001"]}
        position={[0, 0, 2.21]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials["Material.004"]}
        position={[-0.91, -0.17, -0.04]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.02}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={materials["Material.001"]}
        position={[-1, -0.17, -0.05]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.16}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials["Material.001"]}
        position={[-0.91, -0.17, -0.05]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={1.05}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials.Material}
        position={[-0.45, 0.42, -2.18]}
        rotation={[0, 0.24, 0]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials["Material.004"]}
        position={[-0.8, -0.17, 1.3]}
        rotation={[0, 0, -Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Retopo_Lancer_Evolution_10001.geometry}
        material={materials["Material.001"]}
        position={[-0.88, 0.38, -1.09]}
        rotation={[0, -0.02, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials["Material.007"]}
        position={[-0.4, 1, 0.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.08, -0.01, 0.08]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.011"]}
        position={[-0.92, 0.31, 1.33]}
      />
    </group>
  );
}

useGLTF.preload("/garage/car-c.glb");
